USE [master]
GO

/****** Object:  Database [Books]    Script Date: 14/3/2023 20:15:53 ******/
CREATE DATABASE [Books]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Books', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Books.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Books_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Books_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Books].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Books] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Books] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Books] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Books] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Books] SET ARITHABORT OFF 
GO

ALTER DATABASE [Books] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Books] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Books] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Books] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Books] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Books] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Books] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Books] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Books] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Books] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Books] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Books] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Books] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Books] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Books] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Books] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Books] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Books] SET RECOVERY FULL 
GO

ALTER DATABASE [Books] SET  MULTI_USER 
GO

ALTER DATABASE [Books] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Books] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Books] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Books] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Books] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Books] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Books] SET QUERY_STORE = ON
GO

ALTER DATABASE [Books] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Books] SET  READ_WRITE 
GO



/****** Object:  Table [dbo].[BookInformation]    Script Date: 14/3/2023 20:16:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BookInformation](
	[ISBN] [varchar](50) NOT NULL,
	[Photo] [varchar](50) NOT NULL,
	[Title] [varchar](50) NOT NULL,
	[Author] [varchar](50) NOT NULL,
	[ReleaseDate] [varchar](50) NOT NULL,
	[Price] [decimal](18, 0) NOT NULL
) ON [PRIMARY]
GO

/****** Object:  StoredProcedure [dbo].[spGetBooks]    Script Date: 14/3/2023 20:16:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[spGetBooks] 

AS
BEGIN

	SELECT	
		ISBN,
		Photo,
		Title,
		Author,
		ReleaseDate,
		Price
	From BookInformation
END
GO